### ISSUE TITLE
M500 - M600 Voltage limit

### ISSUE THREAD

**Issue by CiDi-IT** [OpenSourceEBike/Bafang_M500_M600#26]
In a system with 48V battery or done the following tests:

- I tried the 48V firmware "CRX10NC4818i132046.7" by changing , the maximum current 20A "0774=14" and the minimum voltage to 38V "076C=26".
The display disconnects the bike at the original voltage of 43V and the current does not exceed the original value of 18A.

- I tried the 43V firmware "CRX10NC4320i132045.6" by changing the nominal voltage to 48V "0770=30" and the maximum to 53V "0768=35".
The display incorrectly indicates the percentage of charge as if the change did not exist.

- I tried the 36V firmware "CRX10NC3625i132047.7" by changing the nominal voltage to 48V "0770=30", the maximum current 20A "0774=14", the minimum to 38V "076C=26" and the maximum to 53V "0768=35".
The display immediately gives an overvoltage error 07.

N.B. I cannot understand where the display takes references to report the % of the battery.
The voltage value is passed to it by the controller via "CAN", but how does it know if the system is at 36 or 43 or 48V?

**Comment by Ornias1993** [comment]
The first was already discovered/discussed in another thread #25 

You can **NOT** change the nominal voltage, I knew this already. There are multiple locations where it's used and I've not yet found/figured all of them. So that explains the second and third issue.
