### ISSUE TITLE
swap controller?

### ISSUE THREAD

**Issue by cpardo13** [OpenSourceEBike/Bafang_M500_M600#36]
hi, 
anyone are interested in swapping their M500 controller for an M600 controller?
Or anyone knows where to buy m500 controller?
Thanks

**Comment by Ornias1993** [comment]
Swapping should work fine, assuming you fix the wiring (which is different).

**Comment by cpardo13** [comment]
I know i have to change the wiring.
My question is.. Anyone wants to swap their m500 controller for my m600 controller.

**Comment by Ornias1993** [comment]
Github issues are not discussion boards, hence thats why it's closed.
Questions about hardware documentation are fine, and your hardware related question is answered.
