### ISSUE TITLE
New firmware M600 36V 18A

### ISSUE THREAD

**Issue by cpardo13** [OpenSourceEBike/Bafang_M500_M600#81]
Hello, 
I have a new firmware from Bafang for M600 36V 18A.
I have compare with the 25A firmware and have a little of bits of diferencies.
I think if a developer or expert compare this two files, know the bits to modify for personalize a firmware. 
Add a link to download the firmware because im not upload to this repository. 

https://we.tl/t-Er6noc3yAk

**Comment by Ornias1993** [comment]
Everyone can open a PR to this repository, please do so.

**Comment by Ornias1993** [comment]
Don't expect others to do that for you... We expect opening a fork, uploading an opening a PR.

**Comment by cpardo13** [comment]
I don't understand sorry. My english is very bad.
I open this issue for share a new firmware because im not can upload directly.
But you're still as nice as ever.

**Comment by Ornias1993** [comment]
Please file a PR (Pull Request), not an issue.
For your needless personal attack i'm going to lock this issue. It's not needed at all.
