### ISSUE TITLE
OpenBafangTool - New Open-Source Bafang Configuration Tool

### ISSUE THREAD

**Issue by andrey-pr** [OpenSourceEBike/Bafang_M500_M600#97]
Hello.
I'm happy to introduce my new open source project - OpenBafangTool.
Currently it supports only bafang motors with UART interface, but I plan to add support of CAN later.
The main goal of project to make modern cross-platform tool to configurate and repair different kinds of modern ebike systems, such as Bafang, Yamaha (right now I'm working on it), Brose and others.
You can download executables for windows and linux (AppImage) and the manual [here](https://github.com/andrey-pr/OpenBafangTool/releases), source code is available [here](https://github.com/andrey-pr/OpenBafangTool).
Currently this project in early alpha phase, so please use it carefully.

Sorry if its not allowed to post info about my project here. Data from this repo helped me a lot, and I would like to collaborate with community of this project.

I'm looking forward for your feedback!

**Comment by Ornias1993** [comment]
Hi, i'm going to close this and will request not to spam this repo again.
As this repo is about the M500-M600 motors which are CANBUS only.
