### ISSUE TITLE
backup firmware m500

### ISSUE THREAD

**Issue by Antorcha70** [OpenSourceEBike/Bafang_M500_M600#98]
Hola, estoy intentando averiguar cómo hacer una lectura del firmware que trae mi M500, ¿se puede hacer?, gracias.
![m500_firmware](https://github.com/OpenSourceEBike/Bafang_M500_M600/assets/163279826/286261d8-8e00-45ab-a09c-8c2b1d99468c)
![m500_firmware2 jpg](https://github.com/OpenSourceEBike/Bafang_M500_M600/assets/163279826/9126db22-6e5f-412f-a6c5-3f9663384f3c)

**Comment by Ornias1993** [comment]
we're an english community here.
